version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "STATE"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
enhancedworkbenches = true
cinderscapes = true
barteringstation = true
mageflame = true
doapi = true
betterfurnacesreforged = true
brewery = true
ribbits = true
dungeonnowloading = true
camping = true
runes = true
refurbished_furniture = true
eldritch_end = true
automobility = true
furniture = true
stoneworks = true
aquamirae = true
darkutils = true
arcanelanterns = true
railways = true
bloomingnature = true
milk = true
amendments = true
herbalbrews = true
ftbquests = true
bakery = true
lookinsharp = true
dankstorage = true
sophisticatedbackpacks = true
netherchested = true
pirates = true
customportalapi = true
spell_engine = true
knightlib = true
nightlights = true
naturalist = true
witcher_rpg = true
minecells = true
redeco = true
supplementaries = true
techreborn = true
create_vibrant_vaults = true
magnumtorch = true
grassoverhaul = true
deeperdarker = true
suppsquared = true
paladins = true
beachparty = true
endrem = true
create = true
cornexpansion = true
echochest = true
yungscavebiomes = true
farm_and_charm = true
extended_drawers = true
wildernature = true
rogues = true
minecraft = true
philipsruins = true
mowziesmobs = true
iceandfire = true
createaddition = true
tradingpost = true
netherexp = true
zenith = true
nethervinery = true
endermanoverhaul = true
ae2 = true
jewelry = true
wetlands = true
bosses_of_mass_destruction = true
creeperoverhaul = true
archers = true
traverse = true
enchantinginfuser = true
valkyrienskies = true
vs_eureka = true
moyai = true
toms_storage = true
vinery = true
fluxnetworks = true
meadow = true
illagerinvasion = true
reinfchest = true
hearth_and_home = true
azurelib = true
