# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				frog = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				stray = true
				item = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				fireball = true
				player = true
				illusioner = true
				villager = true
				wolf = true
				skeleton_horse = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.tide]
				tuna = true
				ocean_perch = true
				bluegill = true
				pike = true
				barracuda = true
				trout = true
				fishing_bobber = true
				guppy = true
				clayfish = true
				mackerel = true
				catfish = true
				bass = true
				sailfish = true
				yellow_perch = true
				mint_carp = true

			[light_sources.settings.entities.grapplemod]
				grapplehook = true

			[light_sources.settings.entities.man_of_many_planes]
				economy_plane = true

			[light_sources.settings.entities.endermanoverhaul]
				mushroom_fields_enderman = true
				savanna_enderman = true
				cave_enderman = true
				flower_fields_enderman = true
				snowy_enderman = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true
				mutant_creeper = true
				mutant_skeleton = true
				mutant_zombie = true
				mutant_arrow = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true
				murk = true
				verdant = true
				thicket = true

			[light_sources.settings.entities.knightquest]
				ratman = true
				eldknight = true
				ghosty = true
				swampman = true
				eldbomb = true
				lizzy = true

			[light_sources.settings.entities.galosphere]
				sparkle = true

			[light_sources.settings.entities.naturalist]
				deer = true
				rattlesnake = true
				zebra = true
				snail = true
				canary = true
				firefly = true
				rhino = true
				hippo = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				lion = true
				vulture = true
				robin = true
				boar = true
				butterfly = true
				giraffe = true
				duck = true
				bear = true
				sparrow = true
				lizard = true
				elephant = true
				finch = true

			[light_sources.settings.entities.wetlands]
				elder_gear_golem = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				bullet = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.frostiful]
				frost_tipped_arrow = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				ice_cube = true

			[light_sources.settings.entities.meadow]
				wooly_cow = true
				water_buffalo = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.bewitchment]
				ghost = true
				werewolf = true
				raven = true
				owl = true
				snake = true

			[light_sources.settings.entities.bakery]
				wandering_baker = true

			[light_sources.settings.entities.wildernature]
				deer = true
				cassowary = true
				owl = true
				pelican = true
				flamingo = true
				boar = true
				raccoon = true
				squirrel = true
				red_wolf = true
				hedgehog = true
				turkey = true
				minisheep = true
				bison = true
				dog = true
				penguin = true

			[light_sources.settings.entities.creeperoverhaul]
				snowy_creeper = true
				ocean_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.iceandfire]
				pixie = true
				cockatrice = true
				lightning_dragon = true
				hippocampus = true
				hippogryph = true
				troll = true
				ice_dragon_charge = true
				fire_dragon = true
				ice_dragon = true
				ghost = true
				deathworm = true
				multipart = true
				dragon_multipart = true
				dragon_skull = true

			[light_sources.settings.entities.smallships]
				cog = true

			[light_sources.settings.entities.supplementaries]
				rope_arrow = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true
				crab = true
				rascal = true

			[light_sources.settings.entities.bloomingnature]
				wandering_gardener = true

