
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Error rendering overlay"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Error rendering overlay"]

