version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
azurelib = true
bountiful = true
tide = true
seasonsextras = true
mutantmonsters = true
more_spawners = true
barteringstation = true
simple_copper_pipes = true
doapi = true
betterfurnacesreforged = true
betternether = true
brewery = true
ribbits = true
dungeonnowloading = true
betterend = true
friendsandfoes = true
runes = true
refurbished_furniture = true
comforts = true
aquamirae = true
railways = true
bloomingnature = true
phantasm = true
milk = true
amendments = true
herbalbrews = true
frostiful = true
bakery = true
lookinsharp = true
bewitchment = true
sophisticatedbackpacks = true
end_reborn = true
gravestones = true
spell_engine = true
knightlib = true
customportalapi = true
naturalist = true
nightlights = true
techreborn = true
minecells = true
supplementaries = true
create_vibrant_vaults = true
deeperdarker = true
suppsquared = true
paladins = true
beachparty = true
create = true
echochest = true
extended_drawers = true
yungscavebiomes = true
farm_and_charm = true
interiors = true
wildernature = true
rogues = true
minecraft = true
createaddition = true
iceandfire = true
tradingpost = true
expandedstorage = true
towers = true
scorchful = true
netherexp = true
wetlands = true
nethervinery = true
ae2 = true
jewelry = true
endermanoverhaul = true
waystones = true
immersive_weathering = true
creeperoverhaul = true
archers = true
vinery = true
toms_storage = true
create_power_loader = true
illagerinvasion = true
meadow = true
fluxnetworks = true
grapplemod = true
