#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 01 21:05:36 GMT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.6 + EuphoriaPatches_1.7.0
